<?php
/**
 * Authors: Alex Gusev <alex@flancer64.com>
 * Since: 2018
 *
 * @var \Praxigento\Odoo\Block\Adminhtml\Catalog\Replicate\Products\Index $block
 */

/**
 * Form fields names see in \Praxigento\Odoo\Block\Adminhtml\Catalog\Replicate\Products\Report::REQ_
 * (This is inversion, because names should be defined in this file and be used in the Report-block,
 * but I don't know how to do it).
 */
$wrhsItems = $block->getSelectItemsForWarehouses();
?>
<div id="prxgt_admin_form_container" style="width: 90%; margin: 0 auto; border: 0px solid black;">
    <form id="prxgt_admin_from"
          method="post"
          action="<?= $block->getUrlSubmit() ?>">
        <input name="form_key"
               type="hidden"
               value="<?= $block->getFormKey() ?>"/>

        <fieldset class="fieldset admin__fieldset">

            <!-- SKU text input -->
            <div class="admin__field field field-report_type with-note">
                <label class="label admin__field-label"
                       for="prxgt_admin_from_sku"><?= __('SKU') ?>:</label>
                <div class="admin__field-control control">
                    <input id="prxgt_admin_from_sku"
                           name="sku"
                           class="admin__control-text admin__control-text input-text"
                           type="text">
                    <div class="note admin__field-note">Comma-separated list of product's SKUs to replicate
                        (ABC-21,QWE-34; if omitted - all products will be replicated).
                    </div>
                </div>
            </div>

            <!-- Warehouse select: there are some troubles with multi-select in Magento. -->
            <div class="admin__field field field-report_type with-note">
                <label class="label admin__field-label"
                       for="prxgt_admin_from_warehouses"><?= __('Warehouse') ?>:</label>
                <div class="admin__field-control control">
                    <select id="prxgt_admin_from_warehouses"
                            name="warehouses"
                            disabled="true"
                            class="multiselect-custom admin__control-select">
                        <?php foreach ($wrhsItems as $value => $label): ?>
                            <option value="<?= $value ?>"><?= $label ?></option>
                        <?php endforeach; ?>
                    </select>
                    <div class="note admin__field-note" id="report_type-note">Warehouse code to replicate (if omitted
                        - products for all warehouses will be replicated).
                    </div>
                </div>
            </div>

        </fieldset>

        <div style="float: right; margin-left: 0px; margin-top:0px;">
            <button id="prxgt_admin_form_submit"
                    title="<?= __('Replicate Products') ?>"
                    type="submit"
                    class="action-default scalable primary">
                <span><?= __('Replicate Products') ?></span>
            </button>
        </div>
    </form>
</div>